In [6]:
import pandas as pd
import yfinance as yf
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go


# 1. Set up the Prior

In [7]:
assets = ["NVDA", "TSM", "MSFT", "GOOG", "AMZN", "META", "TSLA"]
assets.sort()
start_date = '2015-01-01'
end_date = '2024-12-31'

In [8]:
# data = yf.download(assets, start=start_date, end=end_date)['Close']
# data.to_csv('TechSavvy_assetPrice.csv')

In [9]:
assets_data = pd.read_csv('TechSavvy_assetPrice.csv')
assets_data.index = pd.to_datetime(assets_data['Date'])
assets_data.drop(columns=['Date'], inplace=True)
assets_data.head()

AMZN       GOOG       META       MSFT      NVDA       TSLA  \
Date                                                                        
2015-01-02  15.4260  26.045292  78.082001  40.072132  0.483099  14.620667   
2015-01-05  15.1095  25.502361  76.827919  39.703636  0.474939  14.006000   
2015-01-06  14.7645  24.911289  75.792793  39.120903  0.460540  14.085333   
2015-01-07  14.9210  24.868612  75.792793  39.617935  0.459340  14.063333   
2015-01-08  15.0230  24.947023  77.813271  40.783421  0.476619  14.041333   

                  TSM  
Date                   
2015-01-02  16.790493  
2015-01-05  16.383539  
2015-01-06  16.097170  
2015-01-07  16.330788  
2015-01-08  16.436293

In [10]:
return_data = assets_data.pct_change()
return_data = return_data.iloc[1:]
return_data

AMZN      GOOG      META      MSFT      NVDA      TSLA  \
Date                                                                     
2015-01-05 -0.020517 -0.020846 -0.016061 -0.009196 -0.016890 -0.042041   
2015-01-06 -0.022833 -0.023177 -0.013473 -0.014677 -0.030318  0.005664   
2015-01-07  0.010600 -0.001713  0.000000  0.012705 -0.002605 -0.001562   
2015-01-08  0.006836  0.003153  0.026658  0.029418  0.037617 -0.001564   
2015-01-09 -0.011749 -0.012951 -0.005628 -0.008405  0.004028 -0.018802   
...              ...       ...       ...       ...       ...       ...   
2024-12-23  0.000622  0.015703  0.024947 -0.003092  0.036897  0.022657   
2024-12-24  0.017729  0.008062  0.013170  0.009374  0.003938  0.073572   
2024-12-26 -0.008732 -0.002379 -0.007240 -0.002777 -0.002068 -0.017630   
2024-12-27 -0.014534 -0.015525 -0.005867 -0.017302 -0.020868 -0.049479   
2024-12-30 -0.010950 -0.006957 -0.014288 -0.013240  0.003503 -0.033012   

                 TSM  
Date                  
2015-01-05 -0.024237  
2015-01-06 -0.017479  
2015-01-07  0.014513  
2015-01-08  0.006460  
2015-01-09 -0.027968  
...              ...  
2024-12-23  0.051468  
2024-12-24 -0.004967  
2024-12-26 -0.015848  
2024-12-27 -0.007042  
2024-12-30 -0.006150  

[2514 rows x 7 columns]

In [11]:
# market_caps = pd.DataFrame({'Asset': assets, 'Market Cap': ''})
# # columns are asset ticker and blank values

# for asset in assets:
#     mcap = yf.Ticker(asset).info['marketCap']
#     market_caps.loc[market_caps['Asset'] == asset, 'Market Cap'] = mcap

# market_caps.to_csv('TechSavvy_marketCaps.csv')

In [12]:
market_caps = pd.read_csv('TechSavvy_marketCaps.csv')
market_caps.drop(columns=['Unnamed: 0'], inplace=True)
market_caps

Asset     Market Cap
0  AMZN  2180052811776
1  GOOG  2091000791040
2  META  1586856591360
3  MSFT  2937611616256
4  NVDA  2944836042752
5  TSLA   926808080384
6   TSM   938246799360

In [13]:
mkt_weights = pd.Series(market_caps['Market Cap'].values, index=market_caps['Asset']) / market_caps['Market Cap'].sum()
mkt_weights

Asset
AMZN    0.160234
GOOG    0.153689
META    0.116634
MSFT    0.215915
NVDA    0.216446
TSLA    0.068121
TSM     0.068961
dtype: float64

In [14]:
cov_matrix = return_data.cov() * 252
cov_matrix

AMZN      GOOG      META      MSFT      NVDA      TSLA       TSM
AMZN  0.107492  0.060430  0.072670  0.058567  0.080929  0.072641  0.044362
GOOG  0.060430  0.081252  0.066994  0.055168  0.072680  0.059150  0.042375
META  0.072670  0.066994  0.140598  0.059380  0.087209  0.068615  0.048854
MSFT  0.058567  0.055168  0.059380  0.073674  0.079351  0.062015  0.044755
NVDA  0.080929  0.072680  0.087209  0.079351  0.236291  0.111089  0.092230
TSLA  0.072641  0.059150  0.068615  0.062015  0.111089  0.326760  0.065893
TSM   0.044362  0.042375  0.048854  0.044755  0.092230  0.065893  0.102172

risk_aversion = $\delta = \frac{R - R_f}{\sigma^2}$

In [15]:
# sp500 = yf.Ticker('^GSPC')
# sp500_data = sp500.history(start='2010-01-01', end='2024-12-31')['Close']
# sp500_data.to_csv('TechSavvy_sp500.csv')

In [16]:
sp500_data = pd.read_csv('TechSavvy_sp500.csv')
sp500_data.index = pd.to_datetime(sp500_data['Date'], utc=True)
sp500_data.drop(columns=['Date'], inplace=True)
sp500_data.head()

Close
Date                                  
2010-01-04 05:00:00+00:00  1132.989990
2010-01-05 05:00:00+00:00  1136.520020
2010-01-06 05:00:00+00:00  1137.140015
2010-01-07 05:00:00+00:00  1141.689941
2010-01-08 05:00:00+00:00  1144.979980

In [17]:
risk_free_rate = 0.03

In [18]:
market_prices = sp500_data['Close'].squeeze()
market_rets = market_prices.pct_change().dropna()
r = market_rets.mean() * 252
var = market_rets.var() * 252
risk_aversion = (r - risk_free_rate) / var
risk_aversion

np.float64(3.2064723876715333)

In [19]:
Pi = risk_aversion * cov_matrix.dot(mkt_weights)
Pi

AMZN    0.234575
GOOG    0.207070
META    0.250358
MSFT    0.209005
NVDA    0.373600
TSLA    0.298109
TSM     0.193926
dtype: float64

# 2. Express investors' view

In [20]:
P = np.array([
    [1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1], 
    [0, 0, -1, 1, 0, 0, 0], 
], dtype=float)

Q = np.array([2, 0.2, 0.3], dtype=float)
Q

array([2. , 0.2, 0.3])

In [21]:
# omega = uncertainty of the investor's views
# Since we assume views are independent, the omega is a diagonal matrix
# the larger the value, the less confidence in the views
omega = np.diag([0.002, 0.002, 0.003])
omega

array([[0.002, 0.   , 0.   ],
       [0.   , 0.002, 0.   ],
       [0.   , 0.   , 0.003]])

In [22]:
# tau = uncertainty of the prior (equilibrium) returns
# the smaller tau is, the more weight is given to the market view
tau = 0.025

# 3. Black Litterman Posterior Mean

In [23]:
def black_litterman_posterior(tau, Sigma, P, Omega, Pi, Q):
    tau_Sigma = tau * Sigma
    tau_Sigma_inv = np.linalg.inv(tau_Sigma)
    Omega_inv = np.linalg.inv(Omega)
    left_term = tau_Sigma_inv + P.T @ Omega_inv @ P
    left_term_inv = np.linalg.inv(left_term)
    right_term = tau_Sigma_inv @ Pi + P.T @ Omega_inv @ Q
    return left_term_inv @ right_term

post_rets = black_litterman_posterior(tau, cov_matrix, P, omega, Pi, Q)
post_rets

array([1.18826354, 0.69299472, 0.6921722 , 0.72787785, 0.95720726,
       0.86328344, 0.39104047])

In [24]:
# find the difference between Pi and post_rets
post_rets - Pi

AMZN    0.953688
GOOG    0.485925
META    0.441814
MSFT    0.518873
NVDA    0.583608
TSLA    0.565174
TSM     0.197114
dtype: float64

# 4. New Optimal Weights

In [25]:
def black_litterman_posterior_weights(delta, posterior_returns, posterior_cov, assets):
    posterior_cov_inv = np.linalg.inv(posterior_cov)
    weights = (1.0 / delta) * (posterior_cov_inv @ posterior_returns)
    weights = weights / weights.sum()
    weights = pd.Series(weights, index=assets)
    return weights

# I didn't use posterior covariance matrix but the original covariance matrix
# because I only want to see the difference between the original and posterior weights
# and keep the change in the model small
# this is the same approach as Pypfopt's BlackLittermanModel
post_weights = black_litterman_posterior_weights(risk_aversion, post_rets, cov_matrix, assets)
post_weights


AMZN    0.972214
GOOG    0.044942
META   -0.166752
MSFT    0.263998
NVDA    0.063294
TSLA    0.019920
TSM    -0.197615
dtype: float64